feat: fix workflow

diff --git a/.github/workflows/docker-deploy-render.yml b/.github/workflows/docker-deploy-render.yml
--- a/.github/workflows/docker-deploy-render.yml
+++ b/.github/workflows/docker-deploy-render.yml
@@ -1,4 +1,4 @@
-name: Build and Deploy Docker image to Render
+name: Build and Deploy Docker image to Render.com
 
 # Ensure the GITHUB_TOKEN has permissions to push to GHCR (packages: write)
 permissions:
@@ -7,7 +7,7 @@ permissions:
 
 on:
   push:
-    branches: [ dev ]
+    branches: [ master ]
 
 env:
   IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/sb-ecom
@@ -42,21 +42,22 @@ jobs:
             ${{ env.IMAGE_NAME }}:${{ github.sha }}
           platforms: linux/amd64
 
-#      - name: Trigger deploy on Render
-#        # Only run this step if the branch is main
-#        env:
-#          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}&imageURL=${{IMAGE_NAME}}:latest
-#        run: |
-#          if [ -z "$deploy_url" ]; then
-#            echo "Missing RENDER_DEPLOY_HOOK_URL secret. Aborting.";
-#            exit 1;
-#          fi
-#          if [ -z "${secrets.RENDER_DEPLOY_HOOK_URL}" ]; then
-#            echo "Missing RENDER_DEPLOY_HOOK_URL. Aborting.";
-#            exit 1;
-#          fi
-#          echo "Triggering deploy for Render service $RENDER_SERVICE_ID"
-#          curl "$deploy_url"
+      - name: Trigger deploy on Render
+        # Only run this step if the branch is main
+        env:
+          SPRING_PROFILES_ACTIVE: prod
+          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}&imageURL=${{IMAGE_NAME}}:latest
+        run: |
+          if [ -z "$deploy_url" ]; then
+            echo "Missing RENDER_DEPLOY_HOOK_URL secret. Aborting.";
+            exit 1;
+          fi
+          if [ -z "${secrets.RENDER_DEPLOY_HOOK_URL}" ]; then
+            echo "Missing RENDER_DEPLOY_HOOK_URL. Aborting.";
+            exit 1;
+          fi
+          echo "Triggering deploy for Render service $RENDER_SERVICE_ID"
+          curl "$deploy_url"
 
 #      - name: Trigger deploy on Render
 #        env:
